# Copyright 2017-2018 by Aldrin J D'Souza.
# Licensed under the MIT License <https://opensource.org/licenses/MIT>

conventions:
  categories:
    - {tag: "feature", title: "Features"}
    - {tag: "break", title: "Breaking Changes"}
